logonhistory:
    path:     /
    defaults: { _controller: "MyAppCrediWireBundle:LogonHistory:index" }

logonhistory_show:
    path:     /{id}/show
    defaults: { _controller: "MyAppCrediWireBundle:LogonHistory:show" }

logonhistory_new:
    path:     /new
    defaults: { _controller: "MyAppCrediWireBundle:LogonHistory:new" }

logonhistory_create:
    path:     /create
    defaults: { _controller: "MyAppCrediWireBundle:LogonHistory:create" }
    requirements: { _method: post }

logonhistory_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyAppCrediWireBundle:LogonHistory:edit" }

logonhistory_update:
    path:     /{id}/update
    defaults: { _controller: "MyAppCrediWireBundle:LogonHistory:update" }
    requirements: { _method: post|put }

logonhistory_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyAppCrediWireBundle:LogonHistory:delete" }
    requirements: { _method: post|delete }
